-- Performance decisions documented inline. See CLAUDE.md for the full architecture.
--
-- UNLOGGED: skips WAL (Write-Ahead Log) writes entirely. This table stores ephemeral
-- data with a 24h TTL — crash-recovery durability is unnecessary, and the WAL savings
-- are significant on write-heavy workloads (every INSERT/UPDATE/DELETE avoids WAL I/O).
-- Trade-off: the table is NOT replicated to standbys and is truncated on crash recovery.
-- Acceptable here because idempotency entries can be safely regenerated by client retries.

CREATE UNLOGGED TABLE IF NOT EXISTS idempotency_keys (
    -- UUID (16 bytes fixed) instead of TEXT (~37 bytes variable).
    -- Smaller PK index → more keys per 8KB page → better cache hit rate.
    -- Fixed-width comparisons avoid collation overhead. The application filter
    -- already validates UUID format before any store call.
    key          UUID        NOT NULL PRIMARY KEY,

    -- Always exactly 64 hex chars (SHA256). CHAR(64) avoids varlena overhead
    -- that TEXT would introduce. Not indexed, so the gain is modest — mostly
    -- schema correctness.
    request_hash CHAR(64)    NOT NULL,

    -- Identifies the lock owner. Generated by TryAcquire, validated by
    -- Complete and Release. Prevents a stale caller (whose sentinel expired
    -- and was re-acquired by another request) from corrupting the new owner's
    -- state. Written once on INSERT, never modified — preserves HOT eligibility.
    -- Not indexed: only used in WHERE alongside the PK.
    ownership_token  UUID        NOT NULL,

    status_code  INT         NULL,         -- NULL = in-progress (lock held)

    -- JSON instead of JSONB. Headers are stored and retrieved whole — never
    -- queried with @>, ?, or GIN operators. JSON skips the binary decomposition
    -- on write, making INSERT/UPDATE cheaper.
    headers      JSON        NULL,

    body         BYTEA       NULL,         -- captured response body
    expires_at   TIMESTAMPTZ NOT NULL
)
-- fillfactor = 50: reserves 50% free space per heap page for HOT (Heap-Only Tuple)
-- updates. The sentinel row written by TryAcquire has NULLs for status_code,
-- headers, and body; Complete then fills them in, growing the tuple significantly.
-- 50% accommodates this growth on the same page, which is what makes HOT possible.
-- HOT updates skip index maintenance entirely — critical for write-heavy workloads.
-- Trade-off: pages are half-empty initially, but the table rarely exceeds tens of
-- thousands of rows (24h TTL), so the extra disk usage is negligible.
WITH (fillfactor = 50);

-- INDEX DECISION: no secondary indexes.
--
-- The previous schema had a partial index on (expires_at) WHERE status_code IS NOT NULL.
-- That index covered two columns modified by Complete (status_code transitions
-- NULL → non-NULL, expires_at is refreshed). Because PostgreSQL's HOT optimization
-- requires that NO indexed column is modified, the partial index forced a full
-- index-entry creation on every Complete UPDATE — expensive MVCC overhead on
-- the hottest write path.
--
-- Dropping it enables HOT for every Complete UPDATE (only the PK column `key`
-- is indexed, and it is never modified).
--
-- Eviction queries now fall back to sequential scan, which is acceptable because:
--   1. The table stores ephemeral data with 24h TTL — it stays small.
--   2. Eviction is probabilistic (~10% of requests) and bounded (100 rows per run).
--   3. The PK index on `key` still covers all point lookups (acquire, complete, release).
